gallows = {
    0: ('              ',
        '              ',
        '              ',
        '              ',
        '              ',
        '              ',
        'TTTTTTTTTTTTTT'),
    1: ('   +          ',
        '   |          ',
        '   |          ',
        '   |          ',
        '   |          ',
        '  /|\\         ',
        'TTTTTTTTTTTTTT'),
    2: ('   +-++-+     ',
        '   |/         ',
        '   |          ',
        '   |          ',
        '   |          ',
        '  /|\\         ',
        'TTTTTTTTTTTTTT'),
    3: ('   +-++-+     ',
        '   |/   |     ',
        '   |          ',
        '   |          ',
        '   |          ',
        '  /|\\         ',
        'TTTTTTTTTTTTTT'),
    4: ('   +-++-+     ',
        '   |/   |     ',
        '   |    O     ',
        '   |          ',
        '   |          ',
        '  /|\\         ',
        'TTTTTTTTTTTTTT'),
    5: ('   +-++-+     ',
        '   |/   |     ',
        '   |    O     ',
        '   |          ',
        '   |          ',
        '  /|\\   T     ',
        'TTTTTTTTTTTTTT'),
    6: ('   +-++-+     ',
        '   |/   |     ',
        '   |    O     ',
        '   |       O  ',
        '   |      /|\\ ',
        '  /|\\   T / \\ ',
        'TTTTTTTTTTTTTT'),
    7: ('   +-++-+     ',
        '   |/   |     ',
        '   |    0     ',
        '   |   /|\\    ',
        '   |    Y     ',
        '  /|\\   T     ',
        'TTTTTTTTTTTTTT'),
    8: ('   +-++-+     ',
        '   |/   |     ',
        '   |    @     ',
        '   |   /|\\    ',
        '   |   / \\    ',
        '  /|\\         ',
        'TTTTTTTTTTTTTT'),
}
possibleErrors = len(gallows) - 1
